### ISSUE TITLE
Fails with poor error message if /etc/nsswitch.conf is missing

### ISSUE THREAD

**Issue by ghost** [pikhq/musl-nscd#3]
If `/etc/nsswitch.conf` is missing, nscd fails to run with following message:
```
# /musl-nscd-1.0.1/obj/nscd 
nscd: No such file or directory
```

This error persists even after `touch /etc/nsswitch.conf`.

**Comment by the-maldridge** [comment]
Very unhelpful indeed, I just ran into this today trying to debug another problem.  Is there a way to at least print that that file wasn't found?  Usually this kind of output means the linker wasn't found.
