### ISSUE TITLE
How does this compare against something like skarnet's nsss?

### ISSUE THREAD

**Issue by firasuke** [pikhq/musl-nscd#34]
How does this project compare against something like [skarnet's nsss](https://skarnet.org/software/nsss/)?

**Comment by ericonr** [comment]
Unless someone implements a nscd-like backend for nsss, musl-nscd is the only solution allows one to use the nss modules that are expected to be dynamically loaded into each process with musl.

For now, nsss only has a unix backend (which musl already checks via local files - though slower) and a nslcd backend (which provides LDAP).

musl-nscd, OTOH, supports any existing nss module.

**Comment by firasuke** [comment]
I see.

I suppose that `shadow`'s nscd doesn't work with musl?

**Comment by ericonr** [comment]
Where do you see shadow having a nscd implementation? I only see a function that calls `nscd -i` to flush the nscd cache.

**Comment by firasuke** [comment]
`shadow` comes with a configuration flag `--with-nscd` which supposedly enables support for `nscd`, which I think can be passed when using `musl-nscd` on a musl based system?

**Comment by firasuke** [comment]
@ericonr Kindly have a look at [this](https://inbox.vuxu.org/musl/20201103154104.GV534@brightrain.aerifal.cx/t/).

**Comment by ericonr** [comment]
> shadow comes with a configuration flag --with-nscd which supposedly enables support for nscd, which I think can be passed when using musl-nscd on a musl based system?

It does enable support for nscd, as in support for flushing the nscd cache when editing host files. musl-nscd doesn't support the `-i` flag used for this purpose, so enabling the option in shadow just makes for a slightly useless error message. It will make the tools behave a bit better if they are compiled statically and moved to a glibc system, though.

> @ericonr Kindly have a look at this.

I know about that thread. What do you mean to show by it?

**Comment by firasuke** [comment]
I see, thanks for your thoughts on this.

> I know about that thread. What do you mean to show by it?

It's nscd/musl related so I figured I'd post it here (for future visitors as well).

Thanks again, this has been very informative! Closing now.
