### ISSUE TITLE
Some problems with the Strxfrm() function and the Wcsxfrm() function in the MUSL Lic 

### ISSUE THREAD

**Issue by jiaozhouxiaojia** [pikhq/musl-nscd#9]
When I was referring to your code, I found that there were some problems with the Strxfrm() function and the Wcsxfrm() function in the MUSL Lic library. The two functions are located in the  “musl-1.1.23\src\locale”  directory. 

 As for the Strxfrm() function, when n = l or n < l, the copy string function is not executed.
    As for the Wcsxfrm() function, when n = 1, l = 2, a character of the source string is not copied, but only one ‘\0’.
    In response to the above questions, I made the following changes:
```
size_t __strxfrm_l(char *restrict dest, const char *restrict src, size_t n, locale_t loc)
{
	size_t l = strlen(src);
	if (l < n) {
		stpncpy(dest, src, l+1);
	} else if (n) {
		stpncpy(dest, src, n);
	}
	return l;
}


size_t __wcsxfrm_l(wchar_t *restrict dest, const wchar_t *restrict src, size_t n, locale_t loc)
{
	size_t l = wcslen(src);
	if (l < n) {
		wmemcpy(dest, src, l+1);
	} else if (n) {
		wmemcpy(dest, src, n-1);
		dest[n-1] = 0;
	}
	return l;
}
```

**Comment by the-maldridge** [comment]
Edited to enable code formatting.

I also think that your patch may be sent to the wrong repo, as musl is a library dependency of this codebase.

**Comment by ericonr** [comment]
POSIX specifies that if the return value of `strxfrm` is equal to or greater than `n`, the contents of the destination buffer are unspecified. So the function doesn't need to be fixed.

The last relevant change to wcsxfrm was f1471d32166e0881dccc1d551b59238a07351668, and the code is the same as it's shown here.

>  As for the Wcsxfrm() function, when n = 1, l = 2, a character of the source string is not copied, but only one ‘\0’.

When `n=1`, there's only room for the null character, nothing else.
